name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests suite

    steps:
    - uses: actions/checkout@v2
      with:
        # We need the full history for gitCreated/gitLastUpdated to works as expected
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Tests
      run: ./build.sh test
